# Harjoitus 5

## Harjoituksen tarkoitus

Harjoituksen tarkoituksena on testata Django verkkokehyksen toimivuutta kehitysvaiheessa ja tuotannossa.

Aloitetaan tekemällä webbisovellus, jolla on simppeli CRUD. Opetuskerran aikana ehdinkin jo asentaa virtuaaliympäristön ja luoda oman projektin. Requiremenets teksitiedostoon määritellään asennettava paketti (Django), jotta pip osaa sentaa sen. Pip on työväline Python-pakettien asennukseen.


>sudo apt-get install virtualenv (asennetaan virtuaaliympäristö)
>
>virtualenv --system-site-packages -p python3 env/ (luodaan uusi virtuaaliympäristö)
>
>source env/bin/activate (käynnistetään virtuaaliympäristö)
>
>micro requirements.txt Django (määritellään asennettavat Python-paketit)
>
>pip install requirements.txt (asennetaan paketit)
>
>django-admin startproject sampsaco (aloitetaan uusi projekti)
>
>./manage.py runserver (testataan toimiiko; kyllä toimii)
>
>./manage.py startapp appointments (tehdään uusi tietokanta ajanvarauksille)
>
>micro sampsaco/settings.py (käydään lisäämässä kanta projektin määrityksiin)
>
>micro crm/appointments.py (lisätään luokka, sille attribuutit description, client, strattime, endtime) 
>
>./manage.py makemigrations & ./manage.py migrate (lisätään luokkiin tehdyt muutokset tietokantaan)
>
>micro appointments/admin.py (rekisteröitään tietokanta, jotta se näkyy /admin endpointissa)

Käydäänpä katsomassa näkyykö Appointments taulu sovelluksessamme. Navigoidaan siis localhost/admin ja kirjaudutaan sisään tunnilla luoduilla tunnuksilla. Admin tunnukset luotiin komennolla ./manage.py createsuperuser. 

![Image](/django/appointments1.png "404")
![Image](/django/appointments2.png "404")

Kyllä, kanta toimii eikä sen luomisessa ilmennyt yhtään ongelmia. Lisäsin kantaan myös yhden testitapaamisen ja se näyttää sen ilman ongelmia.

![Image](/django/appointments3.png "404")

Tietueen nimi on kannassa kuitenkin 'Appointment object (1)' ja tätähän me emme halua. Käydäänpä siis muuttamassa Appointment luokan palautuslauseketta. Navigoitaan taas models.py tiedostoon ja lisätään sinne funktio joka palauttaa tapaamisen kuvauksen ja ajankohdan. Huomasin myös, että aikaisemmin unohdin lisätä date-attribuutin, ja käytössäni oli vain kellonajat. Lisätään mukaan siis date attribuutti, importataan Pythonin datetime (from datetime import datetime) ja laitetaan sovellus palauttamaan tapaamisen kuvaus ja aika.

>def __str__(self):
>
>        return self.description + ' Päivä: ' +  self.date.strftime("%D")

![Image](/django/appointments4.png "404")

Nyt palautus näyttää järkevämmältä! Seuraavaksi lisätään pari käyttäjää.

## Käyttäjät

Käyttäjien lisääminen ja hallinnointi onnistuu kätevästi Djangon käyttöliittymällä. Kuten kuvasta näkyy, meillä on tällä hetkellä vain yksi käyttäjä (admin).

![Image](/django/user1.png "404")

Lisätäänpä pari testikäyttäjää 'Add New User' - valikosta. Nimetään ne TestiKayttaja01 ja TestiKayttaja02. Annetaan TestiKayttaja01:selle sudo oikeudet, eli hän voi muokata mitä tahansa ilman eksplisiittiä lupaa. Toiselle käyttäjälle annan luvat manuaalisesti. Alemmassa kuvassa TestiKayttaja02:sen manuaalisesti määritellyt oikeudet ja ylemmässä TestiKayttaja01:sen määritellyt sudo-oikeudet.

**TestiKayttaja01:**

![Image](/django/user2.png "404")

**TestiKayttaja02:**

![Image](/django/user3.png "404")

Kokeillaanpa kirjautua ykköskäyttäjälle ja muokkaamassa Appointments taulukkoa; onnistuu. Käyttäjällä voi itseasiassa tehdä kaiken minkä adminillakin, eli poistaa käyttäjiä, tauluja ja muokata kaikkea. TestiKayttaja01 on siis käytännössä samassa asemassa kuin admin.

Testataan TestiKayttaja02:sta. Hänelle on annettu oikeudet vain appointments-taulun katseluun ja uusien tapaamisten lisäykseen. Näinhän se toimiikin, eli tällä käyttäjällä en pysty poistamaan tai muokkaamaan tapaamisia, vain lisäämään ja katselemaan niitä. Käyttäjiä ei tällä pääse muokkaamaan.

## Tuotantoon

Harjoitustietokanta ja -käyttöliittymä ovat nyt valmiita, mutta haluaisimme ne oletettavasti myös webbiin, eli tarvitsemme webbipalvelimen. Tällaisen me loimmekin aikaisemmassa harjoituksessa (https://github.com/sampsale/LinuxPalvelimet/blob/master/h3.md) Apache2:sta käyttäen. Mutta miten saamme Djangolla luodun sovelluksen näkymään palvelimessamme? 

Aloitetaen luomalla staattinen esimerkkisivu kotikansioomme ja luodaan sinne html-tiedosto.

>mkdir -p publicwsgi/sampsaco/static/
>
>micro index.html

Käydäänpä laittamassa tämä hakemisto (/home/sampsa/publicwsgi/sampsaco/static/) Apache2:sen määrityksiin. Navigoitaan siis /etc/apache2/sites-available ja luodaan sinne sampsaco.conf - konfigurointitiedosto, johon määritellään tuon staattisen sivun polku. 

![Image](/django/sampsaconf.png "404")

Pistetään tämä oma sivumme oletussivuksi ja suljetaan vanha oletus. Apache2 bootataan.

>sudo a2ensite sampsaco.conf
>
>sudo a2dissite 000-default.conf 
>
>systemctl reload apache2

Testataanpa urlia http://localhost/static/ ja katsotaan toimiiko uusi staattinen sivu. Kyllä toimii!

![Image](/django/testisivu.png "404")

Seuraavaksi olisi tarkoitus saada Django toimimaan tuotantopalvelimella. Navigoidaanpa taas publicwsgi kansioon ja luodaan sinne virtuaaliympäristö kuten aikaisemmin.

>virtualenv -p python3 --system-site-packages env
>
>source env/bin/activate
>
>which pip (tarkistetaan että oikea virtuaaliympäristö käytössä, eikä esim aikaisempi)

Samalla kaavalla kuin aikaisemmin, eli luodaan requirements.txt, asennetaan Django ja luodaan uusi projekti.

>Django projektin hakemisto: /home/sampsa/publicwsgi/sampsaco2
>
>Hakemisto jossa wsgi.py konfigurointitiedosto: /home/sampsa/publicwsgi/sampsaco2/sampsaco2
>
>Hakemisto jossa virtuaaliympäristön paketit: /home/sampsa/publicwsgi/env/lib/python3.9

Mennäänpä taas konfigurointitiedostoon Apache2 asetuksissa. Tällä kertaa määrityksiä on paljon ja on tunnustettava, että en tiedä mitä läheskään kaikki tekevät. Ohjeessa jota noudatan (lähteissä) löytyy kuitenkin tarkat ohjeet, joten kokeillaanpa.

>sudoedit /etc/apache2/sites-available/sampsaco.conf

![Image](/django/sampsaconf2.png "404")

Asennetaan Apachen wsgi-moduuli, jotta Apache tunnistaa syntaksin ja osaa kommunikoida Djangon kanssa. Bootataan Apache.

>sudo apt-get -y install libapache2-mod-wsgi-py3
>
>systemctl reload apache2

Navigoidaan selaimella localhostiin ja kuin ihmeen kautta Django toimii, eikä konfiguraatiossa ilmennyt ongelmia!

![Image](/django/django.png "404")

Käydäänpä ottamassa debug-asetus pois päältä. Emmehän halua käyttäjien näkevän tarkkoja error-koodeja tai tiedostopolkuja. Kokeilemalla endpointtia joka ei toimi, esimerkiksi localhost/test, antaa Django tarkan virhekuvauksen asiasta, joka olisi massiivinen tietoturva-aukko mikäli se päätyisi tuotantoon asti.

Mennään siis projektin setting.py tiedostoon ja muokataan sitä hieman. Annetaan allowed host kenttään arvot 'localhost' ja 'leikas.me'. Pistetään myös tärkein, eli Debug pois päältä (Debug = False). Nyt sivu ei anna error-koodeja vääristä urleista, vaan se herjaa 'not found'.

Luodaanpa uusi käyttäjä, jotta pääsemme kirjautumaan sivuille.

>./manage.py createsuperuser

Tällä hetkellä sivulla ei ole mitään tyylittelyä (CSS). Mennäänpä setting.py tiedostoon muuttamaan asia.

>micro sampsaco2/settings.py
>
>import os
>
>STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
>
>./manage.py collectstatic

BASE_DIR oli aikaisemmin määritelty Apachen konfiguraatiosta ja static tiedoston loimmekin. Haetaan CSS siis sieltä. Noudetaan vielä staattiset tiedostot roottiin.

![Image](/django/css.png "404")

## Lähteet:
* https://www.geeksforgeeks.org/datetimefield-django-models/?ref=lbp
* https://appdividend.com/2022/02/02/how-to-convert-datetime-to-string-in-python/
* https://terokarvinen.com/2022/django-instant-crm-tutorial/
* https://terokarvinen.com/2021/linux-palvelimet-ict4tn021-3018/#h5